GET http://localhost:8080 HTTP/1.1

###

POST http://localhost:8080 HTTP/1.1
Content-Type: application/json

{
    "from": "example@example.com",
    "subject": "Is it working",
    "query": "Hello there!<br/>Is it working?"
}